//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 08:44:04 PM AST 
//


package com.kunal.customers;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kunal.customers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kunal.customers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateCustomerRequest }
     * 
     */
    public CreateCustomerRequest createCreateCustomerRequest() {
        return new CreateCustomerRequest();
    }

    /**
     * Create an instance of {@link CustomerDetails }
     * 
     */
    public CustomerDetails createCustomerDetails() {
        return new CustomerDetails();
    }

    /**
     * Create an instance of {@link CreateCustomerResponse }
     * 
     */
    public CreateCustomerResponse createCreateCustomerResponse() {
        return new CreateCustomerResponse();
    }

    /**
     * Create an instance of {@link GetCustomerDetailsRequest }
     * 
     */
    public GetCustomerDetailsRequest createGetCustomerDetailsRequest() {
        return new GetCustomerDetailsRequest();
    }

    /**
     * Create an instance of {@link GetCustomerDetailsResponse }
     * 
     */
    public GetCustomerDetailsResponse createGetCustomerDetailsResponse() {
        return new GetCustomerDetailsResponse();
    }

    /**
     * Create an instance of {@link GetAllCustomerDetailsRequest }
     * 
     */
    public GetAllCustomerDetailsRequest createGetAllCustomerDetailsRequest() {
        return new GetAllCustomerDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllCustomerDetailsResponse }
     * 
     */
    public GetAllCustomerDetailsResponse createGetAllCustomerDetailsResponse() {
        return new GetAllCustomerDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteCustomerDetailsRequest }
     * 
     */
    public DeleteCustomerDetailsRequest createDeleteCustomerDetailsRequest() {
        return new DeleteCustomerDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteCustomerDetailsResponse }
     * 
     */
    public DeleteCustomerDetailsResponse createDeleteCustomerDetailsResponse() {
        return new DeleteCustomerDetailsResponse();
    }

}
