//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 08:44:04 PM AST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.kunal.soapws.com/customers", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kunal.customers;
